use std::{
    fmt::Write as _,
    fs,
    path::{Path, PathBuf},
};

use anyhow::{Context, Result, bail};
use clap::Parser;
use palette::{IntoColor, LinSrgb, Oklab, Oklch, Srgb};
use serde::Deserialize;

pub const RAMP_STEPS: usize = 12;
pub const ANSI_HUES: [&str; 8] = [
    "black", "red", "green", "yellow", "blue", "magenta", "cyan", "white",
];
const HUE_RAMP_START_CHROMA_SCALE: f32 = 0.18;
const SPLIT_SURFACE_BG_MIX: f32 = 0.92;
const SPLIT_SURFACE_FG_MIX: f32 = 0.82;

#[derive(Debug, Clone, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "kebab-case")]
pub enum Tone {
    Dark,
    Light,
}

impl Tone {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Dark => "dark",
            Self::Light => "light",
        }
    }
}

#[derive(Debug, Clone, Deserialize, PartialEq, Eq)]
pub struct ThemePalette {
    pub bg: String,
    pub fg: String,
    pub black: String,
    pub red: String,
    pub green: String,
    pub yellow: String,
    pub blue: String,
    pub magenta: String,
    pub cyan: String,
    pub white: String,
}

impl ThemePalette {
    pub fn accent(&self, name: &str) -> Option<&str> {
        match name {
            "black" => Some(&self.black),
            "red" => Some(&self.red),
            "green" => Some(&self.green),
            "yellow" => Some(&self.yellow),
            "blue" => Some(&self.blue),
            "magenta" => Some(&self.magenta),
            "cyan" => Some(&self.cyan),
            "white" => Some(&self.white),
            _ => None,
        }
        .map(String::as_str)
    }
}

#[derive(Debug, Clone, Deserialize, PartialEq, Eq)]
pub struct ThemeDefinition {
    pub name: String,
    pub display_name: String,
    pub author: String,
    pub tone: Tone,
    pub split_surface: bool,
    pub palette: ThemePalette,
    #[serde(default)]
    pub tags: Vec<String>,
}

#[derive(Debug, Parser, PartialEq, Eq)]
pub struct Cli {
    #[arg(long)]
    pub catalog: PathBuf,
    #[arg(long)]
    pub output: PathBuf,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CssColor(String);

impl CssColor {
    pub fn to_hex(&self) -> &str {
        &self.0
    }
}

pub fn parse_hex_color(hex: &str) -> Result<CssColor> {
    Ok(CssColor(normalize_hex(hex)?))
}

pub fn interpolate_oklab(start: &str, end: &str, steps: usize) -> Result<Vec<String>> {
    if steps < 2 {
        bail!("ramps require at least 2 steps");
    }

    let start_rgb = srgb_from_hex(start)?;
    let end_rgb = srgb_from_hex(end)?;
    let start_lab = to_oklab(start_rgb);
    let end_lab = to_oklab(end_rgb);
    let mut ramp = Vec::with_capacity(steps);

    for index in 0..steps {
        let t = index as f32 / (steps.saturating_sub(1)) as f32;
        let interpolated = Oklab::new(
            start_lab.l + (end_lab.l - start_lab.l) * t,
            start_lab.a + (end_lab.a - start_lab.a) * t,
            start_lab.b + (end_lab.b - start_lab.b) * t,
        );
        let linear: LinSrgb = interpolated.into_color();
        ramp.push(hex_from_srgb(Srgb::from_linear(linear)));
    }

    if let Some(first) = ramp.first_mut() {
        *first = normalize_hex(start)?;
    }
    if let Some(last) = ramp.last_mut() {
        *last = normalize_hex(end)?;
    }

    Ok(ramp)
}

pub fn generate_neutral_ramp(palette: &ThemePalette) -> Result<Vec<String>> {
    interpolate_oklab(&palette.bg, &palette.fg, RAMP_STEPS)
}

pub fn generate_hue_ramp(palette: &ThemePalette, name: &str) -> Result<Vec<String>> {
    let target = palette
        .accent(name)
        .with_context(|| format!("unknown palette hue `{name}`"))?;
    let background = srgb_from_hex(&palette.bg)?;
    let target_rgb = srgb_from_hex(target)?;
    let background_oklch = to_oklch(background);
    let target_oklch = to_oklch(target_rgb);
    let ramp_start = Oklch::new(
        background_oklch.l,
        target_oklch.chroma * HUE_RAMP_START_CHROMA_SCALE,
        target_oklch.hue,
    );
    let ramp_start_linear: LinSrgb = ramp_start.into_color();
    let ramp_start_hex = hex_from_srgb(Srgb::from_linear(ramp_start_linear));

    interpolate_oklab(&ramp_start_hex, target, RAMP_STEPS)
}

pub fn render_theme_css(theme: &ThemeDefinition) -> Result<String> {
    let mut css = String::new();
    writeln!(css, "/* Generated by theme-gen — do not edit manually */")?;
    writeln!(
        css,
        "/* Theme: {} | Author: {} | Tone: {} */",
        theme.display_name,
        theme.author,
        theme.tone.as_str()
    )?;
    css.push_str(&render_palette_block(
        &format!(
            "[data-theme=\"{}\"][data-tone=\"{}\"]",
            theme.name,
            theme.tone.as_str()
        ),
        &theme.palette,
    )?);

    if theme.split_surface {
        css.push('\n');
        css.push_str(&render_palette_block(
            &format!("[data-theme=\"{}\"] .editor-surface", theme.name),
            &derive_split_surface_palette(theme)?,
        )?);
    }

    Ok(css)
}

pub fn generate_theme_files(catalog_path: &Path, output_dir: &Path) -> Result<usize> {
    let catalog = fs::read_to_string(catalog_path)
        .with_context(|| format!("failed to read catalog {}", catalog_path.display()))?;
    let themes: Vec<ThemeDefinition> = serde_json::from_str(&catalog)
        .with_context(|| format!("failed to parse catalog {}", catalog_path.display()))?;

    fs::create_dir_all(output_dir)
        .with_context(|| format!("failed to create output directory {}", output_dir.display()))?;
    clear_output_dir(output_dir)?;

    for theme in &themes {
        let css = render_theme_css(theme)?;
        let output_path = output_dir.join(format!("{}.css", theme.name));
        fs::write(&output_path, css)
            .with_context(|| format!("failed to write {}", output_path.display()))?;
    }

    Ok(themes.len())
}

pub fn run_cli(cli: Cli) -> Result<usize> {
    generate_theme_files(&cli.catalog, &cli.output)
}

fn render_palette_block(selector: &str, palette: &ThemePalette) -> Result<String> {
    let mut block = String::new();
    writeln!(block, "{selector} {{")?;

    for (index, color) in generate_neutral_ramp(palette)?.iter().enumerate() {
        writeln!(block, "  --neutral-{index}: {color};")?;
    }

    for hue in ANSI_HUES {
        for (index, color) in generate_hue_ramp(palette, hue)?.iter().enumerate() {
            writeln!(block, "  --{hue}-{index}: {color};")?;
        }
    }

    writeln!(block, "}}")?;
    Ok(block)
}

fn derive_split_surface_palette(theme: &ThemeDefinition) -> Result<ThemePalette> {
    let (surface_anchor, text_anchor) = match theme.tone {
        Tone::Dark => (&theme.palette.white, &theme.palette.black),
        Tone::Light => (&theme.palette.black, &theme.palette.white),
    };

    Ok(ThemePalette {
        bg: mix_hex_oklab(&theme.palette.bg, surface_anchor, SPLIT_SURFACE_BG_MIX)?,
        fg: mix_hex_oklab(&theme.palette.fg, text_anchor, SPLIT_SURFACE_FG_MIX)?,
        black: theme.palette.black.clone(),
        red: theme.palette.red.clone(),
        green: theme.palette.green.clone(),
        yellow: theme.palette.yellow.clone(),
        blue: theme.palette.blue.clone(),
        magenta: theme.palette.magenta.clone(),
        cyan: theme.palette.cyan.clone(),
        white: theme.palette.white.clone(),
    })
}

fn clear_output_dir(output_dir: &Path) -> Result<()> {
    for entry in fs::read_dir(output_dir)
        .with_context(|| format!("failed to read output directory {}", output_dir.display()))?
    {
        let entry = entry?;
        let path = entry.path();
        if path.is_dir() {
            fs::remove_dir_all(&path)
                .with_context(|| format!("failed to remove directory {}", path.display()))?;
        } else {
            fs::remove_file(&path)
                .with_context(|| format!("failed to remove file {}", path.display()))?;
        }
    }
    Ok(())
}

fn mix_hex_oklab(start: &str, end: &str, amount: f32) -> Result<String> {
    let start_rgb = srgb_from_hex(start)?;
    let end_rgb = srgb_from_hex(end)?;
    let start_lab = to_oklab(start_rgb);
    let end_lab = to_oklab(end_rgb);
    let t = amount.clamp(0.0, 1.0);
    let mixed = Oklab::new(
        start_lab.l + (end_lab.l - start_lab.l) * t,
        start_lab.a + (end_lab.a - start_lab.a) * t,
        start_lab.b + (end_lab.b - start_lab.b) * t,
    );
    let linear: LinSrgb = mixed.into_color();
    Ok(hex_from_srgb(Srgb::from_linear(linear)))
}

fn normalize_hex(hex: &str) -> Result<String> {
    let [red, green, blue] = parse_rgb_components(hex)?;
    Ok(format!("#{red:02x}{green:02x}{blue:02x}"))
}

fn parse_rgb_components(hex: &str) -> Result<[u8; 3]> {
    let raw = hex.strip_prefix('#').unwrap_or(hex);
    if raw.len() != 6 {
        bail!("expected a 6-digit hex color, got `{hex}`");
    }

    let parse_pair = |index| -> Result<u8> {
        u8::from_str_radix(&raw[index..index + 2], 16)
            .with_context(|| format!("invalid hex color `{hex}`"))
    };

    Ok([parse_pair(0)?, parse_pair(2)?, parse_pair(4)?])
}

fn srgb_from_hex(hex: &str) -> Result<Srgb<f32>> {
    let [red, green, blue] = parse_rgb_components(hex)?;
    Ok(Srgb::new(
        red as f32 / 255.0,
        green as f32 / 255.0,
        blue as f32 / 255.0,
    ))
}

fn to_oklab(color: Srgb<f32>) -> Oklab {
    let linear = color.into_linear();
    linear.into_color()
}

fn to_oklch(color: Srgb<f32>) -> Oklch {
    let linear = color.into_linear();
    linear.into_color()
}

fn hex_from_srgb(color: Srgb<f32>) -> String {
    fn channel(value: f32) -> u8 {
        (value.clamp(0.0, 1.0) * 255.0).round() as u8
    }

    format!(
        "#{:02x}{:02x}{:02x}",
        channel(color.red),
        channel(color.green),
        channel(color.blue)
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    fn tokyo_night(split_surface: bool) -> ThemeDefinition {
        ThemeDefinition {
            name: if split_surface {
                "manuscript"
            } else {
                "tokyo-night"
            }
            .to_string(),
            display_name: if split_surface {
                "Manuscript"
            } else {
                "Tokyo Night"
            }
            .to_string(),
            author: if split_surface { "Notesmith" } else { "enkia" }.to_string(),
            tone: Tone::Dark,
            split_surface,
            palette: ThemePalette {
                bg: "#1a1b26".to_string(),
                fg: "#c0caf5".to_string(),
                black: "#15161e".to_string(),
                red: "#f7768e".to_string(),
                green: "#9ece6a".to_string(),
                yellow: "#e0af68".to_string(),
                blue: "#7aa2f7".to_string(),
                magenta: "#bb9af7".to_string(),
                cyan: "#7dcfff".to_string(),
                white: "#a9b1d6".to_string(),
            },
            tags: vec!["cool".to_string(), "vibrant".to_string()],
        }
    }

    #[test]
    fn parse_hex_color_round_trips_to_lowercase_hex() {
        let color = parse_hex_color("#1A1B26").expect("hex parses");

        assert_eq!(color.to_hex(), "#1a1b26");
    }

    #[test]
    fn neutral_ramp_has_twelve_steps_with_inclusive_endpoints() {
        let ramp = generate_neutral_ramp(&tokyo_night(false).palette).expect("neutral ramp");

        assert_eq!(ramp.len(), RAMP_STEPS);
        assert_eq!(ramp.first().map(String::as_str), Some("#1a1b26"));
        assert_eq!(ramp.last().map(String::as_str), Some("#c0caf5"));
    }

    #[test]
    fn hue_ramp_has_twelve_steps_and_ends_at_accent_color() {
        let palette = tokyo_night(false).palette;
        let ramp = generate_hue_ramp(&palette, "red").expect("red ramp");

        assert_eq!(ramp.len(), RAMP_STEPS);
        assert_ne!(ramp.first().map(String::as_str), Some(palette.bg.as_str()));
        assert_eq!(ramp.last().map(String::as_str), Some(palette.red.as_str()));
    }

    #[test]
    fn css_output_formats_theme_block_and_split_surface_editor_block() {
        let css = render_theme_css(&tokyo_night(true)).expect("css renders");

        assert!(css.starts_with("/* Generated by theme-gen — do not edit manually */"));
        assert!(css.contains("/* Theme: Manuscript | Author: Notesmith | Tone: dark */"));
        assert!(css.contains("[data-theme=\"manuscript\"][data-tone=\"dark\"] {"));
        assert!(css.contains("  --neutral-0: #1a1b26;"));
        assert!(css.contains("  --red-11: #f7768e;"));
        assert!(css.contains("[data-theme=\"manuscript\"] .editor-surface {"));
    }
}
